language: android
sudo: required
android:
    components:
        - tools
        - build-tools-23.0.2
        - android-23
        - platform-tools-23
        - extra-android-support
        - extra-android-m2repository
        - extra-google-m2repository
    licenses:
        - '.+'

jdk:
    - oraclejdk7

script: "./gradlew assembleDebug"

before_install: "git submodule update --init --recursive"
